### ISSUE TITLE
PCB Fabrication: Suggested settings / pitfalls to avoid?

### ISSUE THREAD

**Issue by zacharyweiss** [Didgitalpunk/UHF-RFID_SAM-interface_Board#1]
Thanks for your work on this! I haven't seen these for sale anywhere so was planning on sending off to JLCPCB/PCBWay to have one fabbed. However, I'm inexperienced with EE / board design / PCB(A) fabrication, so wanted a sanity check from y'all; any specific settings that you would suggest using while exporting to gerber & requesting fabrication? Things I need to avoid / be aware of in the process?

**Comment by Didgitalpunk** [comment]
Heya! you haven't seen these for sale because it's my own design, so noone's making them except me! and also they sold out in a day after I put up the listing ^^ ! I have V2 boards already made, but there's a looooong lead time on the sim slots I use, and no other alternative for them has been found yet, so it'll be a while before they get put up for sale on my tindie...
make sure to join the flipper discord and check out the [UHF | RFID for flipper] project thread to stay up to date :P

If you're inexperienced with pretty much anything PCB related, I'd suggest getting into it first and making a few boards before trying to fab someone else's design, it'll teach you what to look for and how to check their work! god knows V1 had mistakes 🤦‍♀️ 

Also this board uses components you cannot solder without hot air/reflow, so if you don't know how to do that, you're looking at getting them assembled by the board-house, and probably having them source components as well.

**Comment by Didgitalpunk** [comment]
not an issue, just conversation. discord is the place to go for that.
